################################
######                     #####
######     主配置文件       #####
######                     #####
################################


# 环境配置，prod:生产环境。test:测试环境
spring:
  profiles:
    active: test



########################################################################################################################
# mybatis配置
mybatis:
  #config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.honor.simplesbmb.model
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    use-column-label: true




########################################################################################################################
# 指定返回给前端时的时间格式和时区
---
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8