################################
######                     #####
######     测试环境配置      #####
######                     #####
################################

# 服务器配置
server:
  port: 8081
  servlet:
    path: /


spring:
# mysql数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url,username,password动态配置
    url: jdbc:mysql://localhost:3306/xia-test?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxIdle: 100
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 5000
    testOnBorrow: false
    validationQuery: SELECT 1
    testWhileIdle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 30000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 1800000
    numTestsPerEvictionRun: 100
    #为了支持emoji表情
    connectionInitSqls: set names utf8mb4;


#redis配置
---
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址26
    host: localhost
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 0